version: "3"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017-27019:27017-27019'
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - standard

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
    networks:
      - standard

networks:
  standard:
    external: true
